### ISSUE TITLE
firebase 환경 변수 설정 관련 오류

### ISSUE THREAD

**Issue by lolWK** [lolWK/ddingddong-game#15]
# 설명
환경 변수가 제대로 안 가져와지는 문제 확인하기

# Todo

# 기타
undefined로 나온다는 문제를 듣고 확인했고 경로를 바꿔 해결은 했으나, 오류가 뜨고 firebase에 적용이 되지 않음.
보통은 서버측에서 민감한 정보를 처리하는 것 같고 firebase가 제공해주지 않는 기능이라고 해서
일단은 객체로 따로 만들어서 gitignore파일에 추가해 해결했습니다.

문제 발생지 #6

**Comment by gunoc** [comment]
굿~
